import "./globals.css";
import "./fanta.css";


export const metadata = {
  title: "Expenny ⋅ The Subscription Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
